apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd
  namespace: argocd-app
  labels:
    app: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd
        image: hub.pirago.work/argocd:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
