 name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-and-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:${{ github.sha }}

      - name: Update Kubernetes manifest
        run: |
          # Checkout the Kubernetes configuration branch
          git checkout k8s
          
          # Replace the image tag in the deployment file
          sed -i "s|image: .*/your-app:.*|image: ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:${{ github.sha }}|" ci-cd/k8s/base/deployment.yaml
          
          # Commit and push the changes
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ci-cd/k8s/base/deployment.yaml
          git commit -m "chore: Update image tag to ${{ github.sha }}"
          git push
